on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  security_scan:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Semgrep Scan
        uses: returntocorp/semgrep-action@v1
        with:
          generateSarif: "1"
      
      - name: Run Snyk to check for vulnerabilities
        continue-on-error: true
        uses: snyk/actions/docker@master
        
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          image: christinebergen/itas276-nodegoat-cb:latest
          command: test --sarif
          file: ./snyk.sarif

      - name: save report as pipeline artifact
        uses: actions/upload-artifact@v3
        with:
          name: snyk-sca.sarif
          path: snyk.sarif
