name: Assignment 1 DevSecOps standard security pipeline

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
    Start-Notification:
      runs-on: ubuntu-latest
      steps:
        - name: Discord Notification - Jobs Starting
          uses: tsickert/discord-webhook@v5.3.0
          with:
            webhook-url: ${{ secrets.DISCORD_WEBHOOK }}
            username: ${{ github.repository }}
            embed-title: "Security Pipeline jobs are starting..."
            embed-url: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
            embed-description: "SCA-Snyk and SAST-Semgrep jobs are starting for ${{ github.repository }}."
            embed-author-name: ${{ github.actor }}

    SCA-Snyk:
        runs-on: ubuntu-latest
        needs: [Start-Notification]
        steps:
        - uses: actions/checkout@master
        - name: Run Snyk to check Docker image for vulnerabilities
          # Snyk can be used to break the build when it detects vulnerabilities.
          # In this case we want to upload the issues to GitHub Code Scanning
          continue-on-error: true
          uses: snyk/actions/docker@master
          env:
            # In order to use the Snyk Action you will need to have a Snyk API token.
            # See https://docs.snyk.io/integrations/ci-cd-integrations/github-actions-integration#getting-your-snyk-token
            # or you can sign up for free at https://snyk.io/login

            SNYK_TOKEN: ${{secrets.SNYK_TOKEN}}

          with:
            image: christinebergen/itas276-nodegoat-cb:latest
            args: --file=Dockerfile
            sarif: true
        - name: list files    
          run: |
                    ls -lah
           

        - name: save report as pipeline artifact
          uses: actions/upload-artifact@v3
          with:
            name: snyk-sca.sarif
            path: snyk.sarif

    SAST-Semgrep:
        runs-on: ubuntu-latest
        needs: [Start-Notification]
        container:
            image: returntocorp/semgrep

        steps:   
            # Checkout source for scanning
            - name: clone application source code
              uses: actions/checkout@v3

            # Run semgrep default SAST and generate sarif report
            - name: full semgrep scan
              run: | 
                    semgrep \
                    --sarif --output semgrep-sast.sarif \
                    --metrics=off \
                    --config="p/default"
    
            # Upload report
            - name: save report as pipeline artifact
              uses: actions/upload-artifact@v3
              with:
                name: semgrep-sast.sarif
                path: semgrep-sast.sarif
                
    Discord-Notification:
          runs-on: ubuntu-latest
          needs: [SCA-Snyk, SAST-Semgrep]  # This ensures the notification runs after the other jobs
          steps:
            - name: Discord Notification start
              uses: tsickert/discord-webhook@v5.3.0
              with:
                webhook-url: ${{ secrets.DISCORD_WEBHOOK }}
                username: ${{ github.repository }}
                avatar-url: https://gravatar.com/avatar/be5d3fe06696117c467f199ddb4f1aed?s=400&d=robohash&r=g
                embed-title: "Security Pipeline jobs are starting..."
                embed-url: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
                embed-description: "[Action details ${{ github.run_id }}](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})"
                embed-author-name: ${{ github.triggering_actor }}
